sudo: false
language: node_js
node_js: "9.9.0"
before_install:
  - npm i -g npm@latest
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run test:coverage
notifications:
  on_failure: change # always|never
  on_success: never
