sudo: false
language: node_js
node_js: "9.9.9"
cache:
  directories:
    - node_modules
script:
  - npm ci
  - npm run build
  - npm run test:coverage
notifications:
  on_failure: change # always|never
  on_success: never
