sudo: false
language: node_js
node_js: "9.9.0"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
  - yarn run test:coverage
notifications:
  on_failure: change # always|never
  on_success: never
