sudo: false
language: node_js
node_js: "9.6.1"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn
  - yarn run build
  - yarn test
notifications:
  on_failure: change # always|never
  on_success: never
